# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

label.column.Currency=Currency
label.column.Weeks.In.Arrears=Weeks In Arrears(Up To)
label.column.N.Of.Loans=No Of Loans
label.column.Original.Principal=Original Principal
label.column.Original.Interest=Original Interest
label.column.Principal.Paid=Principal Paid
label.column.Interest.Paid=Interest Paid
label.column.Principal.Overdue=Principal Overdue
label.column.Interest.Overdue=Interest Overdue

lable.title.Aging.Summary.in.Weeks=Aging Summary (Arrears in Weeks)

lable.title.group.Branch=Branch
