# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

label.column.Office=Office
label.column.Loan.Officer=Loan Officer
label.column.Client.Account.Number=Client Account Number
label.column.Name=Name
label.column.Product=Product
label.column.Loan.Account.Number=Loan Account Number
label.column.Due.Date=Due Date
label.column.Installment=Installment
label.column.Currency=Currency
label.column.Principal.Due=Principal Due
label.column.Interest.Due=Interest Due
label.column.Fees.Due=Fees Due
label.column.Penalty.Due=Penalty Due
label.column.Total.Due=Total Due
label.column.Total.Overdue=Total Overdue


lable.title.Expected.Payments.By.Date.Basic=Expected Payments By Date - Basic
lable.title.group.Branch=Branch
