# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

label.column.Office/Branch=Office/Branch
label.column.Currency=Currency
label.column.Client.Account.No=Client Account No.
label.column.Client=Client
label.column.Loan.Account.No=Loan Account No.
label.column.Product=Product
label.column.Fund=Fund
label.column.Loan.Amount=Loan Amount
label.column.Total.Repaid=Total Repaid
label.column.Annual.Nominal.Interest.Rate=Annual Nominal Interest Rate
label.column.Disbursed=Disbursed
label.column.Closed=Closed
label.column.Principal.Repaid=Principal Repaid
label.column.Interest.Repaid=Interest Repaid
label.column.Fees.Repaid=Fees Repaid
label.column.Penalties.Repaid=Penalties Repaid
label.column.Loan.Officer=Loan Officer
label.group.title.Branch.Name=Branch Name


lable.title.Obligation.Met.Loans.Details=Obligation Met Loans Details
